
# サービス（コンテナ）の定義
services:
  # Astroアプリケーションのサービス名
  astro-app:
    # カレントディレクトリのDockerfileを使用してビルド
    build: .
    
    # ポートマッピング - ホストの4321番ポートをコンテナの4321番ポートに接続
    # Astroのデフォルトポートは4321
    ports:
      - "4321:4321"
    
    # ボリュームマウントの設定
    volumes:
      # カレントディレクトリをコンテナの/appにマウント（ソースコードの同期用）
      - .:/app
      # node_modulesを匿名ボリュームとしてマウント（パフォーマンス向上のため）
      - /app/node_modules
      # pnpmのキャッシュストアを永続化（パッケージの再利用のため）
      - pnpm-store:/root/.local/share/pnpm/store
    
    # 環境変数の設定
    environment:
      # Astroの開発サーバーをすべてのネットワークインターフェースでリッスン
      - HOST=0.0.0.0
      - PUBLIC_PREVIEW_TOKEN=${STORYBLOK_PREVIEW_TOKEN}
      - PUBLIC_STORYBLOK_TOKEN=${STORYBLOK_PUBLIC_TOKEN}
      - NODE_ENV=development
      
    env_file:  # .envファイルを読み込む設定を追加
      - .env

# 名前付きボリュームの定義
volumes:
  # pnpmのパッケージキャッシュを保存するための永続ボリューム
  pnpm-store: